package com.sparta.WeatherWear.board.enums;

public enum ClothesType {
    SLEEVELESS,SHORT_SLEEVE,DRESS, SHORTS, MINI_SKIRT, LIGHT_SHIRT, LONG_SLEEVE, LEGGINGS,LIGHT_KNIT, SLACKS,BLOUSE,
    KNIT,HOODIE,SWEAT_SHIRT,COTTON_PANTS,JEANS,JACKET, CARDIGAN,SHIRT, TRENCH_COAT, MILITARY_JACKET, STOCKINGS,
    COAT,LEATHER_JACKET,LINED_CLOTHING,PADDED_COAT,SCARF,HEAT_TECH;
}
